### PR TITLE
Fix mysql2 version for Rails 4

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
- Re: https://github.com/brianmario/mysql2#rails--active-record

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
Fixes 
agile web development with rails edition 4 2016-01-28 15-02-29
http://intertwingly.net/projects/AWDwR4/checkdepot-215-40/section-16.html


@vipulnsward pl review

**Comment by vipulnsward** [comment]
LGTM :+1:

**Comment by vipulnsward** [comment]
@prathamesh-sonpatki how are you testing this on Mac? Or still Vagrant currently?

**Comment by prathamesh-sonpatki** [comment]
Still on vagrant. I think we should add check for Rails 3.2 as well as we run it.

**Pull request merged**
