### PR TITLE
Use Rails 5 compatible Ruby version as default

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
Otherwise even bare bone install of Rails 5 is also failing as we were using Ruby 2.1.5 as default and Rails 5 requires Ruby 2.2 or more.

**Comment by prathamesh-sonpatki** [comment]
This didn't fix the issue of tests not running for Rails 5 - http://intertwingly.net/projects/AWDwR4/checkdepot/makedepot.log

@rubys Any way I can debug why it is not running?

**Comment by rubys** [comment]
The code runs on Mac OS/X or Ubuntu.  I have a Vagrant file, and could easily whip up a Dockerfile if you prefer.  Can you email me at rubys@intertwingly.net, and we can work out what works best for you.

**Comment by prathamesh-sonpatki** [comment]
Thanks, sent email.

**Pull request merged**
