### PR TITLE
- If its Rails 5 routes.rb just add the root file directly

### PR DESCRIPTION
**Pull request by vipulnsward**
- Commented contents from routes.rb were removed here https://github.com/vipulnsward/rails/commit/12e5cb5db30f27bab1c44ebff1b3446336305603

### CODE REVIEW

**Comment by vipulnsward** [comment]
cc @rubys . Please correct me if I am wrong with the 'gsub' thing here.

**Comment by rubys** [comment]
The file that is produced looks like this:

    Rails.application.routes.draw do
      get 'store/index'

      resources :products
      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

      # Serve websocket cable requests in-process
      # mount ActionCable.server => '/cable'
    end

    #START_HIGHLIGHT
        root 'store#index', as: 'store'
    #END_HIGHLIGHT

This causes a problem, as 'root' is in the wrong place.

Book pages (both PDF and paper) also have width limits,  so the comment will need to be split, thus:

      # For details on the DSL available within this file, see
      # http://guides.rubyonrails.org/routing.html

**Comment by rubys** [comment]
Note: the comment doesn't have to be changed in Rails itself, it can be changed by makedepot.rb

**Comment by prathamesh-sonpatki** [comment]
Closing in favor of https://github.com/rubys/awdwr/commit/745f1669fa9ac9c1a5eaa173c8acf49234c55d77

**Pull request closed without merging**
