### PR TITLE
Passing :migrate:status results in `db::migrate:status` in gorp

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
Fix for 
agile web development with rails edition 4 2016-01-28 14-39-01

http://intertwingly.net/projects/AWDwR4/checkdepot-215-40/section-10.1.html

**Comment by vipulnsward** [comment]
:+1:

**Comment by vipulnsward** [comment]
@prathamesh-sonpatki I changed a few as well, can you confirm if they look good?

**Comment by prathamesh-sonpatki** [comment]
@vipulnsward where? link?

**Comment by vipulnsward** [comment]
https://github.com/rubys/awdwr/pull/8

**Pull request merged**
