### PR TITLE
- Fix Vagrant README

### PR DESCRIPTION
**Pull request by vipulnsward**
- Fix README for running testrails command
- Added creating of gemrc to stop unnecessary doc downloads

### CODE REVIEW

**Comment by vipulnsward** [comment]
@rubys https://github.com/vipulnsward/awdwr/blob/ac69888663a2955596c72a84657c95f3cccd543d/edition4/makedepot.rb has lots of `rake task` usage instead of `rails`. Perhaps we should have a different directory/file for Rails 5?

**Comment by rubys** [comment]
Take a look at https://github.com/rubys/gorp/blob/master/lib/gorp/commands.rb

Essentially what I have defined is a DSL which mirrors the latest version of Rails, but "under the covers" maps current names to names appropriate to the version being tested.  You can see some rails 2/3 mappings still there :-).  I haven't really started the update to Rail5, but did do "rake test" => "rails test".

**Comment by vipulnsward** [comment]
Yup, I saw https://github.com/rubys/gorp/commit/1f052445d4033e67c2113ea774dc6c1bdf85003f 
For Rails 5, I believe these commands we run on bash (https://github.com/vipulnsward/awdwr/blob/ac69888663a2955596c72a84657c95f3cccd543d/edition4/makedepot.rb#L192) would change too.
Example: that should be `rails db:migrate`

**Comment by rubys** [comment]
so lets make a "db_migrate" command that runs rails/rake based on checking the rails_epoc

**Pull request merged**
